### ISSUE TITLE
Should call SaveChanges after deleting a user

### ISSUE THREAD

**Issue by luis-fss** [JudahGabriel/RavenDB.Identity#50]
RavenDB docs states that [entities can be marked for deletion by using the Delete method, but will not be removed from the server until SaveChanges is called](https://ravendb.net/docs/article-page/6.0/csharp/client-api/session/deleting-entities#session-deleting-entities)

Code in question:
https://github.com/JudahGabriel/RavenDB.Identity/blob/04bd919a8632e0edfb4496fa04f10453963b15d0/RavenDB.Identity/UserStore.cs#L162

Suggestion:
```csharp
DbSession.Delete(user.Id); // It's possible user is already saved to the database. If so, delete him.await

DbSession.SaveChangesAsync(cancellationToken);
```

**Comment by luis-fss** [comment]
I understand your point, it makes sense, thanks for clarifying.

**Comment by jbuedel** [comment]
Hi @JudahGabriel. I understand the rational behind giving the controllers responsibility for calling `SaveChanges`. I don't think I agree with it, but I'm stilling thinking on that. Anyway, I have a question. `RoleStore` _does_ eagerly save by default, but also exposes  `AutoSaveChanges` which can let `RoleStore` behave like `UserStore` and not eagerly save. Is there justification for `RoleStore` behaving differently by default?

Sort of related: I would suggest that eagerly saving should instead be the default (it's is closer to expected behavior, falling into the pit of the success, etc), but then expose `AutoSaveChanges` on the options, which could be used to opt in to deferred save. We've implemented something close to this for our project, which I'd clean up and make a pr if it interests you.  

Thanks

**Comment by JudahGabriel** [comment]
I think that RoleStore code existed before from when I inherited the project. I agree it's not consistent.

I'm opened to a PR that makes auto saving the default, with an option to opt-out.
